### PR TITLE
refactor(web): supporting `.ts` and`.js` config, exported types

### PR DESCRIPTION
**Pull request by reslear**
WIP 🚧

### CODE REVIEW

**Comment by reslear** [comment]
> Any progress with this?

i'm publish version with this changes see https://www.npmjs.com/package/@reslear/capacitor-google-auth/v/1.1.0
but did not have time for testing (I do not know whether it works, need tests)

and this pull have breaking change

**Comment by spaghettiguru** [comment]
Thanks for quick response, @reslear.

I just realized that having .js config support doesn't actually fix the issue with configuration for multiple environments, since there is still need for find/replace in some XML's anyway...

**Comment by reslear** [comment]
@spaghettiguru yes, you're right, but in my case runtime config helpful partially for native ios android, and big helpful for web

**Comment by arzyu** [comment]
> @spaghettiguru yes, you're right, but in my case runtime config helpful partially for native ios android, and big helpful for web
> 
> p.s. if you testing https://www.npmjs.com/package/@reslear/capacitor-google-auth/v/1.1.0 please write a review :) thx

@reslear  I tested it, but got the error: `"GoogleAuth.init()" is not implemented on android`. Am I missing sth.?

```java
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    registerPlugin(com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.class);
  }
}
```

**Comment by arzyu** [comment]
According to the description in the issue [#116](https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/116#issuecomment-864488903), I adjusted the front-end code, but I encountered another error `{message: "Something went wrong"}`.

```ts
import { Device, DeviceInfo } from "@capacitor/device";
import { GoogleAuth } from "@reslear/capacitor-google-auth";

const initAuth = async () => {
  const deviceInfo = await Device.getInfo() as DeviceInfo;

  if (deviceInfo.platform === "web") {
    GoogleAuth.init();
  }

  const user = await GoogleAuth.signIn();
  console.log(user);
};

initAuth();
```

**Comment by joeflateau** [comment]
please merge this. i'm going to have to switch back to .json config temporarily.

**Comment by reslear** [comment]
how to get response type

before

```ts
import { GoogleAuth } from '@codetrix-studio/capacitor-google-auth';

type Await<T> = T extends PromiseLike<infer U> ? U : T
type User = Await<ReturnType<typeof GoogleAuth.signIn>>
type Authentication = Await<ReturnType<typeof GoogleAuth.refresh>>
```

after
```ts
import { User, Authentication } from '@codetrix-studio/capacitor-google-auth';
```

**Comment by FY0u11** [comment]
Merged but still doesn't work with capacitor.config.ts?

**Comment by reslear** [comment]
@FY0u11 already working and used in production, use temp repo https://www.npmjs.com/package/@reslear/capacitor-google-auth

**Pull request merged**
