### PR TITLE
Upgrade to Capacitor 5

### PR DESCRIPTION
**Pull request by tponte**

### CODE REVIEW

**Comment by nolanmclark** [comment]
Validated works in Cap 5. Thanks for the PR!

**Comment by mashanz** [comment]
Nice, just want to make the same PR, but this PR already exist, I will go with this PR then 🚀

**Comment by reslear** [comment]
well, what should we write in the migration instructions?

**Comment by tponte** [comment]
I believe the capacitor migration will cover that. As for the plugin, I think the user just needs to upgrade the version.

**Comment by Torone** [comment]
I think this just works out of the box following the current documentation. When do you plan to merge it?

**Comment by reslear** [comment]
@Torone hi, I will check the documentation and do it next week

**Comment by DanyloKatranGitHub** [comment]
@reslear . Hello. I'm sorry to bother you but when can we expect this PR to be merged?

**Comment by akdasa** [comment]
Thank you, guys, for keeping this plugin up to date. I can't wait for it to be merged.

**Comment by adelabd** [comment]
Hello @reslear, any update about this PR ?

**Comment by mehmetozanguven** [comment]
When will this PR will be merged? Because right now, CapacitorGoogleAuth package is not working. For instance, I have to use pr's name version to be able login with google: `"@codetrix-studio/capacitor-google-auth": "github:younited/CapacitorGoogleAuth",`

**Comment by akdasa** [comment]
We also waited a while for the Apple-auth merge until someone forked it. Once the fork was made, the owner quickly merged his PR :) I don't see any reason not to fork or why this PR hangs for so long. :)

**Comment by reslear** [comment]
@adelabd released, please check [`@codetrix-studio/capacitor-google-auth@3.3.0`](https://www.npmjs.com/package/@codetrix-studio/capacitor-google-auth/v/3.3.0)

**Comment by adelabd** [comment]
Thank you so much @reslear !

**Pull request merged**
