### PR TITLE
release: v3.1.0

### PR DESCRIPTION
**Pull request by reslear**

### CODE REVIEW

**Comment by reslear** [comment]
@parveenkhtkr please release on npm, thx:)

**Comment by reslear** [comment]
before @parveenkhtkr release new version, can use fork https://www.npmjs.com/package/@reslear/capacitor-google-auth@1.1.8

**Comment by adelabd** [comment]
Please release the new version of npm.

Thank you

**Comment by elisechant** [comment]
Until then work around this by installing the exotic: 

`"@codetrix-studio/capacitor-google-auth": "github:CodetrixStudio/CapacitorGoogleAuth#3.0.2",`

**Comment by reslear** [comment]
@adelabd https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/155#issuecomment-1044508167

**Pull request merged**
