### PR TITLE
[Capacitor 4] migration to Capacitor 4

### PR DESCRIPTION
**Pull request by sawaca96**
capacitor 4.0.0 deployed! ([release](https://github.com/ionic-team/capacitor/releases))

follow https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/128

### CODE REVIEW

**Comment by antonijap** [comment]
Please can somebody merge this

**Comment by reslear** [comment]
thx @sawaca96 for contribution ❤️
we have a migration guide https://capacitorjs.com/docs/updating/4-0 please check again, and ping me.

**Comment by sawaca96** [comment]
b2c836c

@reslear Thank you for the opportunity to contribute 🤩

**Comment by reslear** [comment]
@sawaca96 check please https://github.com/CodetrixStudio/CapacitorGoogleAuth/releases/tag/3.2.0

**Pull request merged**
