### PR TITLE
retrieve acces token from google login

### PR DESCRIPTION
**Pull request by martindongo**
To fix issue https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/53, we have integrated the access token, as it is done in the cordova plugin (https://github.com/EddyVerbruggen/cordova-plugin-googleplus)

### CODE REVIEW

**Comment by guigralho** [comment]
I've tested it and works!
Please I also need this working. Could you accept the merge request?

**Comment by albert-mllrdev** [comment]
Can you make a little addition to this PR to allow the api key from google cloud become usable instead of relying on keys from firebase

```diff
public void load() {
   [...]
+   Boolean forceCodeForUseGoogleCloudID = false;
+   Boolean useGoogleCloudID = (Boolean) getConfigValue("useGoogleCloudID");
+   if (useGoogleCloudID != null) {
+      forceCodeForUseGoogleCloudID = useGoogleCloudID;
+   }

-  GoogleSignInOptions.Builder googleSignInBuilder = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
-           .requestIdToken(clientId)
-           .requestServerAuthCode(clientId, forceCodeForRefreshToken)
-           .requestEmail();

+  GoogleSignInOptions.Builder googleSignInBuilder = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN);
  
+  if (!forceCodeForUseGoogleCloudID ){
+     googleSignInBuilder .requestIdToken(clientId).requestServerAuthCode(clientId, forceCodeForRefreshToken).requestEmail();
+  }
   [...]
}
```

**Review by miguelalmeida — APPROVED** [review]

**Comment by snr-lab** [comment]
Can you please accept the merge request?

**Comment by everestkid** [comment]
Please accept

**Comment by livarakotoarinia** [comment]
Hi I'm a developer and in need of this functionnality. Can we know when will you merge this? Please

Thank you

**Comment by mnkprs** [comment]
Can you just keep it up to date and merge please?

**Comment by bCliks** [comment]
Can you please accept the merge request? @parveenkhtkr

**Comment by Monomachus** [comment]
Please merge this...

**Comment by andrey0902** [comment]
Please merge this because we need this feature, I fork branch for and added this code. It works perfectly.

**Comment by hoi4** [comment]
I would also be very interested in this. Thank you :)

**Comment by alfredosalzillo** [comment]
I also need this.

**Comment by alfredosalzillo** [comment]
Any news on when this will be merged if it will be merged?

**Comment by reslear** [comment]
@alfredosalzillo i can add in https://www.npmjs.com/package/@reslear/capacitor-google-auth but need test result, after merge this package

**Comment by alfredosalzillo** [comment]
@reslear yes please

**Comment by reslear** [comment]
@alfredosalzillo testing please https://www.npmjs.com/package/@reslear/capacitor-google-auth/v/1.1.1

**Comment by jakubkoje** [comment]
@reslear Your fork is throwing this error when calling init on web
`Uncaught TypeError: Cannot read property 'scopes' of undefined`

**Comment by emiliam** [comment]
Please merge this fix once conflicts resolved.

**Comment by ASomerN** [comment]
Any update on this merge?

**Comment by hoi4** [comment]
@reslear any news about this? :)

**Comment by reslear** [comment]
@hoi4 need resolve conflicts

**Comment by reslear** [comment]
closed in favor https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/173

**Pull request closed without merging**
