### PR TITLE
Exposing accessToken for web

### PR DESCRIPTION
**Pull request by Monomachus**
Please expose accessToken for web version of the plugin.

### CODE REVIEW

**Comment by parveenkhtkr** [comment]
Thanks!

**Comment by Monomachus** [comment]
Could you please bump the version and push a new one (like 0.0.4) to npm ? I want to use this fix in my project

**Comment by parveenkhtkr** [comment]
Done 🙂

**Comment by Monomachus** [comment]
Awesome, thank you

**Pull request merged**
