### PR TITLE
fixed wrong interface

### LINKED ISSUE #54: what is the option argument that needs to be passed in GoogleAuth.signIn()?
google error
as u can see this is error iam facing right now ? what is the value argument option required by the method?
Ionic info below
```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\Adit\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10
```

### LINKED ISSUE #58: SignIn error and Logout is not found
All working fine, but some weeks ago I find SignIn which accept 1 parameter (now I've put null) but it gives me error, then logout isn't available.

Help, please!

### LINKED ISSUE #59: signin() expected 1 argument but got 0
don't know what to do. documentation dont say. what do?

### PR DESCRIPTION
**Pull request by spaghiajoeojo**
These few lines fix #59, fix #58, and fix #54.

### CODE REVIEW

**Comment by snr-lab** [comment]
Can you please accept this merge request?

**Comment by Adarsh077** [comment]
Please accept this pull request. Because of this wrong interface, I wasted more than an hour on this issue

**Comment by Adarsh077** [comment]
@snr-lab Thanks you any ways 😄

**Comment by JoelAH** [comment]
When will this be published. I am still seeing the old code when i pull using npm

**Pull request merged**
