### PR TITLE
Implement Google GIS for web.

### PR DESCRIPTION
**Pull request by axi**
This is probably a "work in progress".
I'm able to login but:
- I'm not using grantOfflineAccess anymore and I don't know the impacts
- Scope is not used anymore as the "authentication only" functionnality does not need it, again, not sure of the impacts
- I added a third party library (jose) to decode JWT (I just picked one), not sure it the right thing to do (probably not)
- I didn't update changelog nor readme

Let me know

### CODE REVIEW

**Comment by axi** [comment]
The #202 and #231 issues should know about that

**Comment by reslear** [comment]
please use prettier for format

**Comment by reslear** [comment]
thx for contributing :)

you use **Implicit flow** or **Authorization code flow** ?

**Comment by reslear** [comment]
we need use https://developers.google.com/identity/oauth2/web/guides/use-code-model
and then create simple request like

**Comment by axi** [comment]
Authorisation Code Flow require a backend endpoint ("Your backend platform hosts an authorization code endpoint and receives the code"), I'm not sure that's what we want, is it ?

**Comment by axi** [comment]
As written [here](https://developers.google.com/identity/oauth2/web/guides/how-user-authz-works#authentication_only_scopes)

> Several scopes are used only for user authentication: email, profile, and openid. If your app only uses these scopes, consider if a JWT ID Token and [Sign In With Google](https://developers.google.com/identity/gsi/web) for user sign-up and sign-in meets your needs. In most cases, this is the most straightforward and simple method available for user authentication.

There is simpler ways to handle authentication if we only need email, profile and openid scopes

**Comment by reslear** [comment]
maybe there are two ways to implement

**Comment by axi** [comment]
Sure.
Who can decide which implementation is needed ?
Does someone already use this plugin with other scopes than email profile openid ? If the answer is maybe, then it should still be the case after this (and my current implementation is wrong)

**Comment by axi** [comment]
I worked on a new version using implicit workflow, supporting scopes. I'll share it tomorrow

**Pull request closed without merging**
