### PR TITLE
Android refresh method 

### PR DESCRIPTION
**Pull request by CaolanCode**
Hi,

Thanks for you work on the plugin. It's awesome.

I've created a refresh function to return the accessToken and idToken for Android users.
Both IOS and Web have working refresh methods.
Can you guide me to what documentation you like me to contribute for this commit?

### CODE REVIEW

**Comment by reslear** [comment]
write about refresh method

**Comment by CaolanCode** [comment]
## Android Refresh Function
This function should be called when the app is initialized to establish if the user is currently logged in. If true, the function will return an accessToken, idToken and an empty refreshToken. It has the same functionality as the web refresh function. 

### Example
```javascript
  initializeApp() {
    this.platform.ready().then(() => {
      this.checkLoggedIn();
    });
  }
```
```javascript
  checkLoggedIn() {
    GoogleAuth.refresh()
      .then((data) => {
        if (data.accessToken) {
          this.currentToken = data;
          const storedUser = localStorage.getItem('user');
          if (storedUser) {
            this.user = JSON.parse(storedUser);
          }
        }
      })
      .catch((error) => {
        if (error.type === 'userLoggedOut') {
          this.signin();
        }
      });
  }
```

**Comment by reslear** [comment]
yes, but add to https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/master/README.md

**Comment by CaolanCode** [comment]
Will do.

**Comment by CaolanCode** [comment]
I've submitted the documentation to the README.md

**Pull request merged**
